/* Initial V4 content. Future versions are generated by Owner Studio. */
window.SITE_CONTENT = {
  "meta": {
    "siteTitle": "Himanshu Shekhar | Industrial Lubricants Key Account Manager",
    "description": "Commercial portfolio of Himanshu Shekhar, a Key Account Management and Technical B2B Sales professional specialising in industrial lubricants.",
    "updatedAt": "2026-07-19T00:00:00.000Z"
  },
  "ui": {
    "loadingText": "Building the commercial picture…",
    "headerButton": "Contact",
    "scrollLabel": "Scroll",
    "credentialViewerLabel": "Credential viewer",
    "contactEmailLabel": "Email",
    "contactPhoneLabel": "Phone",
    "contactLinkedinLabel": "LinkedIn",
    "contactLocationLabel": "Location",
    "contactStatusLabel": "Status",
    "viewProfileLabel": "View profile ↗",
    "cursorHome": "Home",
    "cursorContact": "Contact",
    "cursorImpact": "See impact",
    "cursorResume": "View résumé",
    "cursorScroll": "Scroll",
    "cursorOpen": "Open",
    "cursorExplore": "Explore",
    "cursorProof": "Proof",
    "cursorEmail": "Email",
    "cursorCall": "Call",
    "cursorLinkedin": "LinkedIn",
    "cursorDownload": "Download this",
    "downloadLabel": "Download",
    "subjectsLabel": "Selected subjects",
    "skillsExpandLabel": "Show all skills",
    "skillsCollapseLabel": "Show fewer"
  },
  "theme": {
    "background": "#F7F7F5",
    "surface": "#FFFFFF",
    "text": "#0A0A0A",
    "muted": "#666666",
    "accent": "#FF4D00",
    "accentSecondary": "#0068FF",
    "border": "#D8D8D8",
    "darkSectionBackground": "#0A0A0A",
    "cursorColor": "#FF4D00",
    "headingFont": "'Inter', 'Helvetica Neue', Arial, sans-serif",
    "bodyFont": "'Inter', 'Helvetica Neue', Arial, sans-serif",
    "baseFontSize": 17,
    "contentWidth": 1240,
    "cornerRadius": 18
  },
  "security": {
    "adminUsername": "HSHEKHAR004",
    "adminHash": "c164fa95a3aec2675944a64c83bee868a0b9f0551bce3ac916b201aba878832b"
  },
  "brand": {
    "initials": "HS",
    "name": "Himanshu Shekhar",
    "role": "Senior Key Account Manager | Industrial Lubricants | Technical B2B Sales",
    "eyebrow": "INDIA + GERMANY · ENERGY + AUTOMOTIVE",
    "headline": "I turn technical lubricant expertise into measurable account growth.",
    "subheadline": "10+ years building industrial relationships, negotiating complex commercial agreements, and translating technical requirements into profitable, long-term business.",
    "primaryButton": "Explore commercial impact",
    "secondaryButton": "View résumé",
    "profileImage": "",
    "profileImageAlt": "Portrait of Himanshu Shekhar"
  },
  "navigation": [
    {
      "label": "Impact",
      "target": "impact"
    },
    {
      "label": "Track record",
      "target": "track-record"
    },
    {
      "label": "Skills",
      "target": "skills"
    },
    {
      "label": "Experience",
      "target": "experience"
    },
    {
      "label": "Education",
      "target": "education"
    },
    {
      "label": "Credentials",
      "target": "credentials"
    },
    {
      "label": "About",
      "target": "about"
    }
  ],
  "sectionOrder": [
    "impact",
    "expertise",
    "track-record",
    "account-system",
    "skills",
    "experience",
    "education",
    "credentials",
    "about",
    "contact"
  ],
  "sections": {
    "impact": {
      "visible": true,
      "eyebrow": "COMMERCIAL IMPACT",
      "title": "Scale that is visible in the numbers.",
      "intro": "Selected results from industrial, institutional, OEM, and channel-based account management."
    },
    "expertise": {
      "visible": true,
      "eyebrow": "WHERE I CREATE VALUE",
      "title": "Technical understanding. Commercial discipline. Customer growth.",
      "intro": "A sales approach built around application fit, stakeholder alignment, pricing discipline, and reliable execution."
    },
    "track-record": {
      "visible": true,
      "eyebrow": "SELECTED COMMERCIAL TRACK RECORD",
      "title": "Experience across the complete lubricant sales cycle.",
      "intro": "Representative, non-confidential examples of the commercial situations and customer environments I have managed."
    },
    "account-system": {
      "visible": true,
      "eyebrow": "MY ACCOUNT SYSTEM",
      "title": "From technical requirement to repeatable business.",
      "intro": "A structured account-management method for complex industrial and institutional customers."
    },
    "skills": {
      "visible": true,
      "eyebrow": "LUBRICANT KAM SKILLS",
      "title": "Built for complex industrial accounts.",
      "intro": "Commercial, technical, interpersonal, digital, and language capabilities aligned specifically with industrial-lubricant Key Account Management."
    },
    "experience": {
      "visible": true,
      "eyebrow": "PROFESSIONAL EXPERIENCE",
      "title": "Commercial experience across India and Germany.",
      "intro": "Industrial energy, automotive OEM, and technical engineering experience across leading organisations."
    },
    "education": {
      "visible": true,
      "eyebrow": "EDUCATION + ANALYTICAL FOUNDATION",
      "title": "Engineering depth strengthened by international business strategy.",
      "intro": "A mechanical-engineering foundation combined with an MBA and applied research in customer prioritisation."
    },
    "credentials": {
      "visible": true,
      "eyebrow": "CREDENTIALS",
      "title": "The evidence behind the profile.",
      "intro": "Selected professional documents are displayed inside the portfolio for quick review."
    },
    "about": {
      "visible": true,
      "eyebrow": "ABOUT",
      "title": "Technical lubricant seller. Commercial account builder.",
      "intro": "A closer view of the experience and working style behind the results."
    },
    "contact": {
      "visible": true,
      "eyebrow": "LET'S TALK",
      "title": "Looking for a Key Account Manager who understands both the machine and the margin?",
      "intro": "I am open to industrial lubricants, technical B2B sales, strategic accounts, and commercial-growth opportunities with international organisations in India."
    }
  },
  "metrics": [
    {
      "value": "10+",
      "label": "Years of professional experience",
      "detail": "Energy, automotive, and engineering"
    },
    {
      "value": "7+",
      "label": "Years in industrial lubricants",
      "detail": "Lubricants, greases, base oils, and AdBlue"
    },
    {
      "value": "80+",
      "label": "Strategic industrial accounts",
      "detail": "Direct account responsibility"
    },
    {
      "value": "USD 12M",
      "label": "Annual portfolio",
      "detail": "Lubricants and industrial products"
    },
    {
      "value": "18%",
      "label": "Revenue growth",
      "detail": "Through account plans and cross-selling"
    },
    {
      "value": "112%",
      "label": "Target achievement",
      "detail": "Annual revenue performance"
    },
    {
      "value": "35%",
      "label": "Customer-base expansion",
      "detail": "Industrial and government segments"
    },
    {
      "value": "1,500+",
      "label": "Additional customers reached",
      "detail": "Through two dealer channels"
    }
  ],
  "capabilities": [
    {
      "number": "01",
      "title": "Strategic account growth",
      "description": "Account planning, customer retention, cross-selling, new-business development, forecasting, and portfolio expansion across industrial and institutional segments.",
      "image": ""
    },
    {
      "number": "02",
      "title": "Technical and consultative selling",
      "description": "Application-focused product discussions, lubricant and base-oil trials, technical-team coordination, OEM specifications, and Total Cost of Ownership conversations.",
      "image": ""
    },
    {
      "number": "03",
      "title": "Commercial negotiation",
      "description": "Pricing, margin management, long-term contracts, supply agreements, price-variation clauses, quotations, tenders, and institutional purchasing environments.",
      "image": ""
    },
    {
      "number": "04",
      "title": "Channel and stakeholder leadership",
      "description": "Dealer performance, regional coordination, senior-stakeholder meetings, technical conferences, customer events, and cross-functional collaboration with sales, technical, R&D, and finance teams.",
      "image": ""
    }
  ],
  "sectorTags": [
    "Industrial lubricants",
    "Greases",
    "Base oils",
    "AdBlue",
    "Automotive",
    "Manufacturing",
    "Heavy industry",
    "Marine",
    "Defence applications",
    "Government and institutional",
    "Lubricant manufacturers",
    "Dealer channels"
  ],
  "commercialSkills": [
    "Strategic Account Planning",
    "Industrial Lubricant Sales",
    "Technical B2B Sales",
    "Consultative Selling",
    "Application-based Value Selling",
    "New Business Development",
    "Customer Retention and Growth",
    "Cross-selling and Upselling",
    "Pricing Strategy",
    "Margin Management",
    "Commercial Negotiation",
    "Contract Negotiation",
    "Long-term Supply Agreements",
    "Price Variation Clauses",
    "Tender and Bid Management",
    "Government and Institutional Sales",
    "Government E-procurement and GeM Awareness",
    "OEM Account Management",
    "Dealer and Distributor Management",
    "Channel Development",
    "Sales Forecasting",
    "Volume and Demand Planning",
    "Revenue Growth",
    "Portfolio Management",
    "Market and Competitor Analysis",
    "CRM and Pipeline Management",
    "Sales Analytics",
    "Product Trials and Application Testing",
    "Technical Customer Support",
    "Lubricant Selection and Application Fit",
    "OEM Approvals and Specifications",
    "Total Cost of Ownership Selling",
    "Base-oil Sales",
    "Marine Lubricants",
    "Greases and Specialty Products",
    "AdBlue Sales",
    "C-level Customer Engagement",
    "Technical Conferences and Customer Events",
    "Order-fulfilment Coordination",
    "Payment and Credit Coordination",
    "Supply-agreement Management",
    "Customer Prioritisation under Supply Constraints"
  ],
  "softSkills": [
    "Executive Communication",
    "Structured Problem-solving",
    "Analytical Thinking",
    "Stakeholder Alignment",
    "Relationship Building",
    "Cross-functional Collaboration",
    "Cross-cultural Collaboration",
    "Customer Orientation",
    "Commercial Judgement",
    "Ownership and Accountability",
    "Adaptability",
    "Decision-making",
    "Presentation and Facilitation",
    "Conflict Resolution",
    "Negotiation Resilience",
    "Priority and Time Management"
  ],
  "softwareSkills": [
    "Microsoft Excel and VBA",
    "Microsoft Power BI",
    "Microsoft PowerPoint",
    "Microsoft Word",
    "SAP R/3: SD, FI and CO",
    "Salesforce CRM"
  ],
  "languageSkills": [
    "English · C1",
    "German · B2",
    "Hindi · Native"
  ],
  "stories": [
    {
      "kicker": "PORTFOLIO GROWTH",
      "title": "Grew a complex industrial account portfolio at scale.",
      "summary": "Managed approximately 80 strategic industrial accounts within a USD 12M annual portfolio, delivering 18% lubricant-revenue growth and 112% target achievement through structured account plans, pricing discipline, and cross-selling.",
      "result": "18% growth · 112% target",
      "image": ""
    },
    {
      "kicker": "INSTITUTIONAL BUSINESS",
      "title": "Worked across tender-led and government purchasing environments.",
      "summary": "Managed commercial requirements involving quotations, long-term contracts, supply terms, price-variation clauses, and public-sector buying processes, including exposure to transport, defence, and maritime applications.",
      "result": "Contracts · Tenders · Pricing",
      "image": ""
    },
    {
      "kicker": "TECHNICAL CONVERSION",
      "title": "Connected application trials with commercial adoption.",
      "summary": "Led industrial product trials and coordinated customer feedback with technical and R&D teams, helping translate application performance into informed product-adoption and account-development decisions.",
      "result": "Trial → Evidence → Adoption",
      "image": ""
    },
    {
      "kicker": "CHANNEL REACH",
      "title": "Extended coverage through a two-dealer network.",
      "summary": "Supported approximately 1,500 additional small customers through dealer channels across Chennai and Bengaluru while directly managing larger industrial requirements and contributing to dealer policy and performance decisions.",
      "result": "2 dealers · 1,500+ customers",
      "image": ""
    },
    {
      "kicker": "SPECIALISED SEGMENTS",
      "title": "Built exposure across marine, defence, and lubricant manufacturing.",
      "summary": "Managed marine-sector requirements for three years and supported lubricant and base-oil supply across maritime, defence, grease-manufacturing, and lubricant-manufacturing applications in southern India.",
      "result": "Marine · Defence · Base oils",
      "image": ""
    }
  ],
  "accountSteps": [
    {
      "number": "01",
      "title": "Diagnose",
      "description": "Understand equipment, application, operating conditions, incumbent product, and the customer's commercial problem."
    },
    {
      "number": "02",
      "title": "Align",
      "description": "Map technical, procurement, finance, operations, and senior decision-makers around a common value case."
    },
    {
      "number": "03",
      "title": "Prove",
      "description": "Coordinate trials, application testing, technical feedback, approvals, and Total Cost of Ownership evidence."
    },
    {
      "number": "04",
      "title": "Negotiate",
      "description": "Build the pricing, quotation, contract, supply, payment, and risk framework required to win responsibly."
    },
    {
      "number": "05",
      "title": "Deliver",
      "description": "Coordinate forecasting, order fulfilment, channel execution, issue resolution, and stakeholder communication."
    },
    {
      "number": "06",
      "title": "Expand",
      "description": "Track revenue, volume, margin, retention, and whitespace opportunities for cross-selling and sustainable growth."
    }
  ],
  "experiences": [
    {
      "role": "Key Account Management (BMW OEM & Tier-1)",
      "company": "Aptiv Services Deutschland GmbH",
      "location": "Unterschleißheim, Germany",
      "dates": "07/2025 – 01/2026",
      "summary": "Commercial account responsibility across automotive OEM and Tier-1 customer programs.",
      "bullets": [
        "Managed commercial quotations and pricing for OEM BMW and Tier-1 accounts across <strong>12 active vehicle programs</strong>.",
        "Coordinated volume planning and order fulfilment across <strong>USD 5M customer programs</strong>, sustaining <strong>98% on-time delivery</strong>.",
        "Negotiated resolution of pricing and billing deviations with customers.",
        "Strengthened OEM key-account relationships through stakeholder management and global dispatch coordination."
      ],
      "image": ""
    },
    {
      "role": "Sales Steering (Intern)",
      "company": "BMW Group",
      "location": "Headquarters, Munich, Germany",
      "dates": "04/2024 – 10/2024",
      "summary": "Sales-planning and executive-reporting exposure at BMW Group headquarters.",
      "bullets": [
        "Analyzed competitor positioning across <strong>25+ model series</strong> for sales planning.",
        "Supported sales and budget planning for 2025 across <strong>USD 120B+ sales volume</strong>.",
        "Automated executive reporting via Excel, reducing reporting time by <strong>80%</strong>.",
        "Analyzed inventory and supply across markets and models for planning.",
        "Identified sales-growth opportunities and volume risks across key markets."
      ],
      "image": ""
    },
    {
      "role": "Key Account Manager (Technical Sales, B2B)",
      "company": "Indian Oil Corporation Limited",
      "location": "Bengaluru and Chennai, India",
      "dates": "08/2015 – 09/2022",
      "summary": "Industrial lubricants, greases, base oils, and AdBlue across direct accounts, institutional customers, specialised segments, and dealer channels in southern India.",
      "bullets": [
        "Managed B2B sales across approximately <strong>80 key industrial accounts</strong>, handling a <strong>USD 12M annual portfolio</strong>.",
        "Grew lubricant revenue by <strong>18%</strong> through strategic account plans and cross-selling across automotive, manufacturing, and heavy-industry segments.",
        "Negotiated pricing, quotations, and high-value commercial contracts, achieving <strong>112% of annual revenue targets</strong>.",
        "Expanded the industrial and government customer base by <strong>35%</strong> through strategic business development.",
        "Negotiated long-term contracts, pricing clauses, and supply agreements with private and institutional customers.",
        "Led product trials with industrial customers, collaborating with technical and R&D teams to support product adoption.",
        "Supported approximately <strong>1,500 additional customers</strong> through two dealer channels across Chennai and Bengaluru.",
        "Managed three years of marine-sector exposure and supported defence, maritime, lubricant-manufacturing, grease-manufacturing, and bulk base-oil requirements.",
        "Coordinated technical conferences, customer events, and senior-stakeholder meetings while contributing to regional commercial and dealer-policy decisions.",
        "Analyzed competitor trends to optimise lubricant pricing and growth."
      ],
      "image": ""
    },
    {
      "role": "Management Trainee",
      "company": "Hindustan Petroleum Corporation Limited",
      "location": "Pune, India",
      "dates": "06/2015 – 08/2015",
      "summary": "Structured exposure to commercial and sales functions in the energy sector.",
      "bullets": [
        "Completed management training across commercial and sales functions."
      ],
      "image": ""
    },
    {
      "role": "Piping Stress Engineer",
      "company": "Technip KT India Limited",
      "location": "Noida, India",
      "dates": "08/2012 – 12/2013",
      "summary": "Engineering foundation in refinery and petrochemical project environments.",
      "bullets": [
        "Designed piping-stress systems for refinery and petrochemical projects."
      ],
      "image": ""
    }
  ],
  "education": [
    {
      "degree": "MBA, International Business",
      "institution": "Technische Hochschule Nürnberg Georg Simon Ohm",
      "location": "Germany",
      "dates": "10/2022 – 07/2026",
      "result": "CGPA 9.0/10 · German equivalent 1.3",
      "description": "International business education strengthened by practical roles at BMW Group and Aptiv in Germany.",
      "details": [
        "Analytical focus on strategic accounts, constrained supply, commercial trade-offs, risk, and structured decision-making."
      ],
      "subjects": [],
      "image": "",
      "certificate": {
        "label": "View MBA degree certificate",
        "type": "pdf",
        "url": "",
        "downloadUrl": "",
        "downloadFilename": "Himanshu_Shekhar_MBA_Degree.pdf"
      }
    },
    {
      "degree": "Bachelor of Engineering, Mechanical Engineering",
      "institution": "University of Mumbai",
      "location": "India",
      "dates": "06/2008 – 06/2012",
      "result": "CGPA 7.6/10 · Distinction · Top 3 of graduating class",
      "description": "Technical foundation supporting application-based discussions across machinery, industrial operations, automotive systems, and lubricant performance.",
      "details": [
        "Combined engineering problem-solving with later commercial, pricing, and strategic-account responsibility."
      ],
      "subjects": [],
      "image": "",
      "certificate": {
        "label": "View engineering degree certificate",
        "type": "pdf",
        "url": "",
        "downloadUrl": "",
        "downloadFilename": "Himanshu_Shekhar_Engineering_Degree.pdf"
      }
    }
  ],
  "thesis": {
    "visible": true,
    "eyebrow": "MBA THESIS · DECISION FRAMEWORK",
    "title": "Customer prioritisation under supply constraints.",
    "subtitle": "A practical framework for deciding which customer programmes to protect when supply cannot satisfy every request.",
    "summary": "Developed a two-stage decision framework combining a non-compensable eligibility gate with six weighted commercial and strategic criteria. The model changes priorities across immediate, recovery, and future horizons, translates scores into clear action bands, and shows managers which customer programmes to protect, support, manage, or defer.",
    "valueStatement": "The result connects account value, compliance, continuity, profitability, and future strategic importance in one repeatable decision process.",
    "frameworkTags": [
      "Eligibility before value",
      "Six weighted criteria",
      "Three decision horizons",
      "Programme-level prioritisation",
      "Protect · Support · Manage · Defer"
    ],
    "summaryDocument": {
      "label": "View executive summary",
      "type": "pdf",
      "url": "",
      "downloadUrl": "",
      "description": "Concise visual summary of the research question, framework, application, and managerial findings."
    },
    "fullDocument": {
      "label": "Read the complete thesis",
      "type": "pdf",
      "url": "",
      "downloadUrl": "",
      "description": "Complete MBA thesis document."
    }
  },
  "gateAchievement": {
    "visible": true,
    "eyebrow": "NATIONAL ENGINEERING ACHIEVEMENT",
    "title": "GATE All India Rank 836",
    "stat": "TOP 0.4%",
    "context": "Approximately 186,000 candidates",
    "description": "A nationally competitive engineering result demonstrating analytical strength, technical discipline, and the ability to perform under high-pressure selection conditions.",
    "tags": [
      "All India Rank 836",
      "Top 0.4% nationally",
      "Engineering aptitude",
      "Analytical problem-solving"
    ]
  },
  "about": {
    "eyebrow": "ABOUT HIMANSHU",
    "title": "Technical lubricant seller. Commercial account builder.",
    "body": "I have spent more than seven years on the revenue-owning side of industrial lubricants: developing strategic accounts, defending value beyond price, converting technical trials, structuring long-term agreements, and coordinating supply across industrial, government, marine, and dealer-channel customers.\n\nMy mechanical-engineering foundation helps me understand the application. My MBA and commercial experience in Germany sharpen how I manage value, risk, data, and long-term customer growth. I bring both sides to a Key Account Manager role: technical credibility with the customer and commercial accountability for the business.",
    "photo": "",
    "photoAlt": "Portrait of Himanshu Shekhar",
    "photoRatio": "4 / 5"
  },
  "documents": [
    {
      "label": "Lubricants KAM Résumé",
      "type": "image",
      "url": "assets/resume-preview.png",
      "downloadUrl": "assets/Himanshu_Shekhar_Lubricants_KAM_CV.pdf",
      "downloadFilename": "Himanshu_Shekhar_Lubricants_KAM_CV.pdf",
      "description": "One-page professional résumé focused on industrial lubricants and technical B2B sales.",
      "visible": true
    }
  ],
  "achievements": [
    "10+ years across energy, automotive, and technical engineering",
    "7+ years in industrial lubricants, greases, base oils, and AdBlue",
    "International commercial exposure across India and Germany",
    "English C1 · German B2 · Hindi native",
    "Excel VBA · Power BI · SAP R/3 · Salesforce"
  ],
  "contact": {
    "email": "h.shekhar004@gmail.com",
    "phone": "+49 177 2004529",
    "phoneHref": "+491772004529",
    "linkedinLabel": "linkedin.com/in/himanshushekhar-profile",
    "linkedinUrl": "https://www.linkedin.com/in/himanshushekhar-profile",
    "location": "Relocating to India · International mobility",
    "availability": "Open to relevant opportunities"
  },
  "footer": {
    "copyright": "© 2026 Himanshu Shekhar",
    "note": "Industrial Lubricants · Technical B2B Sales · Strategic Accounts",
    "ownerLoginLabel": "Owner login"
  }
};
window.SITE_CONTENT_READY = Promise.resolve(window.SITE_CONTENT);
